# Generated by Django 4.2.4 on 2023-08-12 04:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6c5a9c8b-fee9-43a8-80eb-915ab3517c11'), primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b38c9a67-8862-475a-8d85-3585d0a21c1d'), primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.report')),
            ],
        ),
    ]
